version: '3.3'
services:

  #MYSQL DATABASE
   db:
     image: mysql:8.0
     volumes:
       - ./mysql-data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: bitlevel
       MYSQL_USER: testuser
       MYSQL_PASSWORD: root
     ports:
       - 3306:3306

  # PHP MY ADMIN
   phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root