version: '3.3'
services:
   db:
     image: mysql:8.0
     volumes:
       - ./mysql-data:/var/lib/mysql
       - ./mysql-scripts:/docker-entrypoint-initdb.d
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: bitlevel
       MYSQL_USER: testuser
       MYSQL_PASSWORD: root
     ports:
       - 3306:3306
  
  # PHP MY ADMIN
   phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

  # TOMCAT
   web:
    build:
      context: .       
    depends_on:
      - db
    image: tomcat
    volumes:
            - ./target/BitLevel.war:/usr/local/tomcat/webapps/LoginWebApp.war
    ports:
      - '8080:8080'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bitlevel
      MYSQL_USER: testuser
      MYSQL_PASSWORD: root
# volumes:
#     db_vol:      